repository:
    # See https://developer.github.com/v3/repos/#edit for all available settings.

    # The name of the repository. Changing this will rename the repository
    #name: repo-name

    # A short description of the repository that will show up on GitHub
    #description: description of repo

    # A URL with more information about the repository
    #homepage: https://example.github.io/

    # A comma-separated list of topics to set on the repository
    #topics: project, template, project-template

    # Either `true` to make the repository private, or `false` to make it public.
    private: false

    # Either `true` to enable issues for this repository, `false` to disable them.
    has_issues: true

    # Either `true` to enable the wiki for this repository, `false` to disable it.
    has_wiki: false

    # Either `true` to enable downloads for this repository, `false` to disable them.
    has_downloads: false

    # Updates the default branch for this repository.
    default_branch: master

    # Either `true` to allow squash-merging pull requests, or `false` to prevent
    # squash-merging.
    allow_squash_merge: true

    # Either `true` to allow merging pull requests with a merge commit, or `false`
    # to prevent merging pull requests with merge commits.
    allow_merge_commit: true

    # Either `true` to allow rebase-merging pull requests, or `false` to prevent
    # rebase-merging.
    allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:

#    - name: 'website ğŸŒ'
#      color: "#0052CC"
#      description: Website Tasks
#
#    - name: 'support ğŸ«'
#      color: "#d876e3"
#      description: Support Question
#
#    - name: 'show & tell ğŸ§¸'
#      color: "#FEF2C0"
#      description: Show & Tell - The ONLY place you can legally post links to your shit in this community
#
#    - name: 'Q&A â¤ï¸'
#      color: "#E99695"
#      description: Q&A Thread
#
#    - name: 'poll ğŸ“‹'
#      color: "#C2E0C6"
#      description: A Poll
#
#    - name: 'idea ğŸ’¡'
#      color: "#FEF2C0"
#      description: Idea / Suggestion
#
#    - name: 'announcement ğŸ“£'
#      color: "#F9D0C4"
#      description: A broadcast message for everyone's attention
#
#    - name: 'chore ğŸš§'
#      color: "#D93F0B"
#      description: Work that needs to happen
#
#    - name: 'bug ğŸ'
#      color: "#ff0000"
#      description: Something isn't working
#
#    - name: 'discussion ğŸ’¬'
#      color: "#cfd3d7"
#      description: Discussion Thread
#
#    - name: 'enhancement ğŸ”¥'
#      color: "#D93F0B"
#      description: Discussion Thread
#
#    - name: 'style âœ¨'
#      color: "#006B75"
#      description: Discussion Thread
#
#    - name: 'refactor ğŸ”©'
#      color: "#000000"
#      description: Discussion Thread
#
#    - name: 'docs ğŸ“˜'
#      color: "#0075ca"
#      description: Improvements or additions to documentation
#
#    - name: 'epic ğŸ“Œ'
#      color: "#7057ff"
#      description: Work unit containing sub-tasks
#
#    - name: 'feature ğŸš©'
#      color: "#00ff00"
#      description: New feature or request
#
#    - name: 'question â“'
#      color: "#d876e3"
#      description: Support Question
#
#    - name: 'request ğŸ±'
#      color: "#FBCA04"
#      description: Feature request or suggestion
#
#    - name: 'requires response â°'
#      color: "#B60205"
#      description: Response required by admin
#
#    - name: 'good first issue ğŸ†'
#      color: "#0052CC"
#      description: Good first issue for new contributor
#
#    - name: 'help wanted ğŸš¨'
#      color: "#B60205"
#      description: Extra attention is required
#
#    - name: 'stale ğŸ’¤'
#      color: "#C2E0C6"
#      description: Stale Issue
#
#    - name: 'ğŸ”´'
#      color: "#B60205"
#      description: Priority Critical
#
#    - name: 'ğŸŸ '
#      color: "#D93F0B"
#      description: Priority High
#
#    - name: 'ğŸŸ¡'
#      color: "#FBCA04"
#      description: Priority Medium
#
#    - name: 'ğŸŸ¢'
#      color: "#0E8A16"
#      description: Priority Low
#
#    - name: 'ğŸ”µ'
#      color: "#c5def5"
#      description: Priority None
#
#    - name: "can't replicate âŒ"
#      color: "#D4C5F9"
#      description: "STATUS: CLOSED"
#
#    - name: 'duplicate âŒ'
#      color: "#D4C5F9"
#      description: "STATUS: CLOSED"
#
#    - name: "won't fix âŒ"
#      color: "#D4C5F9"
#      description: "STATUS: CLOSED"
#
#    - name: 'DONE âœ…'
#      color: "#0E8A16"
#      description: "STATUS: DONE"

# Collaborators: give specific users access to this repository.
#collaborators:
#    - username: bkeepers
          # Note: Only valid on organization-owned repositories.
          # The permission to grant the collaborator. Can be one of:
          # * `pull` - can pull, but not push to or administer this repository.
          # * `push` - can pull and push, but not administer this repository.
          # * `admin` - can pull, push and administer this repository.
          # permission: push
